### ISSUE TITLE
Inspect lemmas in `tests/specs/lemmas.k` and `tests/specs/mcd/verification.k` for duplicates/generalizations

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1025]

**Comment by Riib11** [comment]
### `:=` vs. `<-`

What is the difference between `M [ K <- V ]` and `M [ K := V ]`.

### #sizeByteArray WIDTH

Combine.

`lemmas.k`:
```k
rule #sizeByteArray(#buf(SIZE, _)[START .. WIDTH]) => WIDTH
  requires #range(0 <= START < SIZE)
   andBool #range(0 < WIDTH <= SIZE -Int START)
```

`verification.k`:
```k
rule #sizeByteArray(_WS [ START .. WIDTH ]) => WIDTH requires 0 <=Int START andBool 0 <=Int WIDTH [simplification]
```

### <Int

Convert to SMT lemmas?

From `lemmas.k`:

```k
rule X <Int X -Int Y => false requires 0 <=Int Y [simplification]
rule X +Int Y <Int X => false requires 0 <=Int Y [simplification]
```

### maxInt, minInt

Convert to SMT lemmas?

From `lemmas.k`:

```k
rule N <=Int maxInt(P, Q) => true requires N <=Int P orBool N <=Int Q  [simplification]
rule minInt(P, Q)         => P    requires P <=Int Q                   [simplification]
```

### Bool

Convert to SMT lemmas?

From `lemmas.k`:

```k
rule B ==Bool false => notBool B [simplification]
```

**Comment by Riib11** [comment]
The difference between `<-` and `:=`:
- `<-` is K's build-in heterogenous map assignment operator
- `:=` is the EVM-specific map operator, where the keys and values are integers of a particular size

For `<Int`, `maxInt,` minInt`, and `Bool` lemmas, its fine to leave them as is. It would only be useful to add smt-lemmas if they were dealing with uninterpreted functions we don't want the SMT solver to get stuck on them. Even though they are seemingly trivial, the SMT solver apparently had trouble with them somewhere. The functions are uninterpreted by K unit they are given rewrite rules as such, so it's required to include rewrite rules like this each place they are needed rather than putting them in `domains.md` or something like that.

**Comment by Riib11** [comment]
Lemma generalization via #1038
