### ISSUE TITLE
Build KEVM, K, and both Backends

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1044]
From a fresh clone of KEVM, we should be able to build it from source. This means these commands work:

```
git clone 'https://github.com/kframework/evm-semantics'
cd evm-semantics
git submodule update --init --recursive
make deps RELEASE=true -j8
make build RELEASE=true -j8
```

Following the build instructions above ^^^, you should make sure that you can also run some of the tests:

```
make test-conformance -j8 # llvm backend
make test-prove -j8 TEST_SYMBOLIC_BACKEND=haskell # haskell backend
make test-prove -j8 TEST_SYMBOLIC_BACKEND=java # java backend
```

### Georgy

- [x] Build dependencies and semantics (`make deps` and `make build`).
- [x] Run the concrete tests (`make test-conformance`)
- [x] Run the symbolic tests (`make test-prove`).

**Comment by geo2a** [comment]
I've made sure the project builds and the tests run on my system (Arch Linux).

The only hiccup I had is that I needed to install [google-glog](https://archlinux.org/packages/community/x86_64/google-glog/) instead of [glog-git](https://aur.archlinux.org/packages/glog-git/), since the latter does not build and seems to be abandoned.

@ehildenb shall I sand a PR against the README.md with the Arch-related change?

**Comment by ehildenb** [comment]
Let's:

- See if `glog` is needed (uninstall, and rebuild).
- If it's needed, update to the newest version, otherwise remove.
