### ISSUE TITLE
More tutorial lessons

### ISSUE THREAD

**Issue by ehildenb** [kframework/evm-semantics#1065]
There are more tutorial lessons out, record your confusions on kframework/k#2033

### Max

- [x] Lesson 9
- [x] Lesson 10
- [x] Lesson 11
- [x] Lesson 12
- [x] Lesson 13
- [x] Lesson 14

### Henry

- [x] Lesson 9
- [x] Lesson 10
- [x] Lesson 11
- [x] Lesson 12
- [x] Lesson 13
- [x] Lesson 14

**Comment by Riib11** [comment]
Some minor notes:

Lesson 9
- Some formatting errors in the table, because of how "paragraphs" within table cells are handled.
- Would be nice to see example of how the `color` attribute is used, since its a little unclear if/what the `color` attribute takes as an arguments (and what are valid colors? I see that certain named colors work)

Lesson 10
- Formatting errors in tables; some of the escaped need double-backslashes
- Link to lesson 11 is broken

Lesson 11
- typo: “provies” => “provides”
