### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by daejunpark** [kframework/evm-semantics#200]
Some profiling shows that roughly 50% of time is spent on non-opcode semantic rules (including gas calculation), and an half of that (i.e., 25% of total) is spent on the push/popCallStacks. Is it possible to improve this?

Below are log files that show how much it took (`System.nanoTime()`) and what is the k cell for each step.

[recommended_target_hash.txt](https://github.com/kframework/evm-semantics/files/1940200/x1.txt)
[proc_reward.txt](https://github.com/kframework/evm-semantics/files/1940201/x3.txt)
[vote.txt](https://github.com/kframework/evm-semantics/files/1940202/x4.txt)

**Comment by ehildenb** [comment]
How did you generate these reports? Can you add an option to `krun` like `--profile` which generates them for any semantics?

**Comment by ehildenb** [comment]
I'm working a bit on removing `push/pop` when it's not needed, but it's difficult because there are many places that state can revert.

I do have one performance enhancement in mind, which is #184. I think this should reduce execution time some. Another option would be to try and fold some of the `#exceptional` checks together into one.

Another would be doing `#exceptional` *before* pushing/popping the state. Then any exceptional opcode will not #push the state, though most opcodes are not exceptional, so not a huge win.

**Comment by ehildenb** [comment]
Execution performance has improved. Closing this as there isn't a specific suggestion for this.
