### ISSUE TITLE
verify issue

### ISSUE THREAD

**Issue by zhang505** [kframework/evm-semantics#207]
i just want to know how to verify a contact. and i want to know what the relationship between EVM and kevm.

**Comment by ehildenb** [comment]
KEVM is a formal specification of the KEVM (like the Yellow Paper), but written in the language K. Because K is executable, we also get a reference interpreter out of it. Because K has logical foundations, we also get a program verifier out of it.

To verify contracts with KEVM, it's best to start over in the repo https://github.com/runtimeverification/verified-smart-contracts. Read through the examples there. Understanding KEVM will help you a lot with that, perhaps you can read http://jellopaper.org for that (which is just a copy of this repository, but nicer formatted).

**Comment by zhang505** [comment]
but how can i know the wrong with a etheruem contract.i have read your example,but i can`t know clearly how does it work.and i try to modify some .k file,and i use the prove instruction,but the output is not i expect.i just think it well tell we what the wrong about my program.in addition,i just want to know,if i give you a contract, would you please give me a flow path about how to verify the contrat use your kevm.thank you very much.i have study your kevm a long time.thanks.

**Comment by ehildenb** [comment]
This isn't an issue with the semantics, so I'm going to close.

For reference, here are some potentially helpful links:

-   Article about using KEVM part 2: https://medium.com/ethworks/formal-verification-for-n00bs-part-1-b4781db2a383
-   Article about using KEVM/KLab part 2: https://medium.com/ethworks/formal-verification-for-n00bs-part-2-proving-the-correctness-of-a-token-74085f5cd6c1
-   KLab tutorial: https://www.youtube.com/watch?v=z4mIo38x1u8&t=1s
