### ISSUE TITLE
Testing EVM Bytecode without knowledge of the kframework

### ISSUE THREAD

**Issue by lukwue** [kframework/evm-semantics#800]
Hello,

I want to test a compiled smart contract. How can I do this?
The Example Usage section from the `Readme `file was very confusing to me. I don't know where the `.json` and `.k` files come from. Is the `.k`-file a smart contract compiled into `K`?
Is it actually possible to test EVM bytecode with `kevm `automatically?
I also couldn't find a tutorial on this.

Thank you very much!

**Comment by ehildenb** [comment]
Hey @lukwue it is possible, but it would be very difficult. Can you clarify what you want to test about your contract? If you're trying to do verification, you should use the K prover, if you're trying to write some unit tests or concrete behavior tests of your contract, there are a few other options.

For example, do you already have a Solidity test-suite setup for your contract? Or do you currently use Truffle (or some other similar RPC-based testing tool) for your contract?

**Comment by lukwue** [comment]
Hi @ehildenb ,

thanks for your quick answer :).
I am writing a bachelor thesis. My job is to program a website where you can automatically analyze your smart contract with different security analyzing tools. So I do not know the contracts in advance.
As far as I understood the kevm-project, it is used to translate a contract into `K` and then prove it against specifications written in `K`. So I thought, I could just take a contract, use this project to automatically translate it into `K` and then prove the contract against some definitions already written in `K`.

Is this possible?

**Comment by ehildenb** [comment]
Hey @lukwue we have two such projects in-flight already, so if you're willing (and allowed to), maybe we can have you help out with those existing projects instead of starting a new one?

One of them is to automatically check that a given Solidity program has certain properties using the KProver (so automated verification). This one does not have a web interface yet, so if you want to help us build the web interface and backend, that would be great! The requirements there would be Haskell and PureScript.

The other is an advanced testing framework for Solidity contracts which enables developers to easily check if their test-suite is complete and otherwise extend it where it isn't. This one already has a web interface (in Haskell and PureScript), but you could help work on backend tools which include random testing and LTL monitoring, or on making the web interface for existing tools work (currently not all the tools are exposed via the interface). You can see the working prototype website at https://sandbox.fireflyblockchain.com.

If either of those interest you, please email me at everett.hildenbrandt@runtimeverification.com and we'll see what we can set up.

Note that making your own interface from scratch is also possible, but we won't be able to provide support other than answering questions about KEVM and it is a pretty large task.

**Comment by lukwue** [comment]
Hey @ehildenb 

Thanks for the offer but this unfortunately is not possible. But your project seems very interesting, so maybe I'll text you in half a year when I'll have time again.

Lukas
